### ISSUE TITLE
Unconfirmed Refs

### ISSUE THREAD

**Issue by sarah-bowe** [bhdirect-ebooks/percival#12]
Even though I have gone through all the refs and confirmed or removed them, when I enter "Percival Finish", it sometimes says I still have unconfirmed refs. 

Right now I'm working on the last volume of _Preaching Through the Bible_ (which includes the index). I removed some of the "scripture" it tagged in the Index through the UI because they should have been links to pages in other volumes instead. But when I ran Percival Finish, there were unconfirmed refs found (even though I had checked to make sure all were confirmed in the Dashboard). And in the code afterwords, I found about 11 instances of `<a data-cross-ref='{"scripture":"","valid":false`.

**Comment by westonlit** [comment]
@sarah-bowe These kinds of issues are why percival normally ignores indexes, but since this index was an entire volume, they were treated as chapters and not ignored. Were all the instances in the index text files, or were they in normal chapters, too?
