### ISSUE TITLE
Percival bug? Moving around <td> location

### ISSUE THREAD

**Issue by matthewthemiller** [bhdirect-ebooks/percival#14]
I made a commit to see if you can recreate this: ExploringBible - `9781535936446`; commit `b34c037`; file `ExploreNT102_body06_chapter04.xhtml (pp. 61-74)`

Started like this:
![01 what i saw](https://user-images.githubusercontent.com/25672008/40068125-7ffbbdde-582d-11e8-96c0-edb707d459c7.png)

What the code said:
![02 what code said](https://user-images.githubusercontent.com/25672008/40068153-8e58c19c-582d-11e8-9432-85da0c4d8dff.png)

Tried to remove with percival UI:
![03 tried to remove here](https://user-images.githubusercontent.com/25672008/40068166-983d0538-582d-11e8-95e9-c6c509a67d78.png)

It repeatedly moved it around:
![04 no worky](https://user-images.githubusercontent.com/25672008/40068177-a165639e-582d-11e8-917a-f81b3e451fde.png)

Looked like this in the code as well: 
![screen shot 2018-05-15 at 10 40 14 am](https://user-images.githubusercontent.com/25672008/40068202-aea5c170-582d-11e8-8ed6-c60e16705926.png)

**Comment by westonlit** [comment]
I'm not sure what is going on here on the Percival side of things, exactly. It's related to identical data in the columns, which I need to dig into more to figure out. As it stands, other more normal issues due to duplicate values have addressed
