### ISSUE TITLE
fix checking unconfirmed refs output status

### ISSUE THREAD

**Issue by CaldwellJT** [bhdirect-ebooks/percival#17]
The dashboard UI says all refs have been confirmed, however, the iTerm view says otherwise.

<img width="1680" alt="screenshot 2018-05-18 13 50 51" src="https://user-images.githubusercontent.com/6131061/40252714-d12a8826-5aa2-11e8-8cb2-e92047d3f28d.png">

**Comment by westonlit** [comment]
:( I'll take a look

**Comment by westonlit** [comment]
✅ fixed in https://github.com/bhdirect-ebooks/percival-ui/commit/f88e1daefe1287670494afd2d217e02cd09d8b79
