### ISSUE TITLE
presence of $ in text causing problems on percival finish

### ISSUE THREAD

**Issue by flintsteel7** [bhdirect-ebooks/percival#8]
After running `percival finish` html was garbled where a `$` occurred in the text.

This example is from chapter10 starting around line 92 of EmbersFlame
It also occurred in chapter09 around line 92 (there was a `$` in the text there as well)
You can see the files in that state here: [ba48deb](https://github.com/bhdirect-ebooks/EmbersFlame/commit/ba48deb3848e08d6d2dfcca7a2db5f4d1085e0e9)

This is what was output:
```
    </section>5,000 a year to be its president. But Lee ascertained that those job offers were based on his fame and not his resident skills, so he graciously turned them down, saying that he had to work for his wages. It would not be right, Lee said, to profit from his fame in light of the great sacrifice by so many associated with it. In addition, he refused the offer of a British nobleman who promised an estate plus
    <body epub:type="bodymatter">
      <section epub:type="chapter">5,000 a year. After thanking the admirer, he declared, “I must abide the fortunes and share the fate of my people.” And perhaps the most telling feature of his character was the refusal of an offer from a Northern life insurance company, which promised </section>
    </body>
  </body>
  <body epub:type="bodymatter">
    <section epub:type="chapter">00,000 per year, </section>
  </body>00,000, or five times the salary of the President of the United States. .&#xA0;. . In <span class="italic">Success</span> magazine, Carver said of the offer, “There was nothing to talk over, and I thanked Mr. Edison in a letter.” Carver made it clear that he would rather stay among “his people” in the South and help them improve themselves.<sup class="fn" id="note-backlink-ch10-4"><a epub:type="noteref" href="EmbersFlame03_back03_footnotes.xhtml#note-ch10-4">4</a></sup>
  <body epub:type="bodymatter">
    <section epub:type="chapter">0,000 simply for the use of his name. He graciously declined, informing his would-be benefactor, “My name is not for sale at any price.”</section>
    <p>Instead, Lee ended up serving as the president of Washington College for
      <body epub:type="bodymatter">
        <section epub:type="chapter">,500 a year because, like Carver, he wanted to give the rest of his life to the education of young people.<sup class="fn" id="note-backlink-ch10-5"><a epub:type="noteref" href="EmbersFlame03_back03_footnotes.xhtml#note-ch10-5">5</a></sup></section>
```
following is an image of the PDF
![screen shot 2017-11-27 at 4 46 17 pm](https://user-images.githubusercontent.com/10226589/33293506-a468295c-d392-11e7-9084-9f8969dcb74c.png)

**Comment by sarah-bowe** [comment]
I also had this problem with the book "[Eating the Elephant](https://github.com/bhdirect-ebooks/EatElephant/tree/master)". However, it didn't do that with every $. Here is an example in chapter 7. It didn't break up lines 111 and 117, but for line 112 it did delete "$1" and added the body and section tags.
![screen shot 2017-12-04 at 3 33 59 pm](https://user-images.githubusercontent.com/26905095/33574973-19abc27a-d909-11e7-9f7e-e86e099fa805.png)

**Comment by sarah-bowe** [comment]
Also, in some of the files, it deleted (or I guess moved them somewhere else within the file) the closing `</section>` and `</body>` tags (sometimes both and other times just `</section>`)
